image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar artifacts/app-order.jar -P:profile=test" -PassThru
build_script:
  - ps: chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"
